# Generated by Django 3.2 on 2021-04-21 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('display_name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('person', models.CharField(max_length=254)),
                ('source', models.CharField(blank=True, max_length=254, null=True)),
                ('dateSaid', models.DateField(blank=True, null=True)),
                ('yearsLived', models.CharField(blank=True, max_length=254, null=True)),
                ('stars', models.DecimalField(blank=True, decimal_places=1, max_digits=1, null=True)),
                ('occupation', models.TextField(blank=True)),
                ('realName', models.CharField(blank=True, max_length=254)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('favorite', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotations.category')),
            ],
        ),
    ]
