# Generated by Django 3.2 on 2021-04-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='source',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='stars',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='yearsLived',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
