# Generated by Django 3.2 on 2021-05-01 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_auto_20210425_0628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
